environment:
  sdk: '^3.5.0'

dependencies:
  bloc: ^8.1.4
  dotenv: ^4.2.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.1.0
  http: ^0.13.4
  provider: ^6.0.0


name: ChatApp
description: A companion app for the Community Forum project

version: 0.0.1