environment:
  sdk: '^3.5.0'

dependencies:
  bloc: ^8.1.4
  dotenv: ^4.2.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.1.0
  font_awesome_flutter: ^10.7.0
  http: ^1.2.2
  material_design_icons_flutter: ^7.0.7296
  material_symbols_icons: ^4.2785.1
  provider: ^6.0.0


name: ChatApp
description: A companion app for the Community Forum project

flutter:
  uses-material-design: true

version: 0.0.1