namespace RestApiServer.Enums
{
    public enum SystemPermissionType
    {
        Users_Create,
        Users_Edit,
        Users_Delete,
        Users_ChangeRoles,
        Users_ChangePassword,
        Users_BanUser,
        Roles_Create,
        Roles_Edit,
        Roles_Delete,
        Threads_Create,
        Threads_Edit,
        Threads_Delete,
        Threads_Lock,
        Threads_Unlock,
        Posts_Create,
        Posts_Edit,
        Posts_Delete,
        Posts_Update,
        Posts_PostImage,
        Posts_PostReply,
        Topics_Create,
        Topics_Edit,
        Topics_Delete,
        Chat_Create,
        Chat_Edit,
        Chat_Delete,
        Chat_PostImage,
        Chat_CreateGroup,
        Chat_EditGroup,
        Chat_DeleteGroup,
        Chat_JoinGroup
    }
}
