namespace RestApiServer.Enums
{
    public enum SystemPermissionType
    {
        Users_Create,
        Users_Edit,
        Users_Delete,
        Users_ChangeRoles,
        Users_ChangePassword,
        Users_BanUser,
        Roles_Create,
        Roles_Edit,
        Roles_Delete,
        Threads_Create,
        Threads_Edit,
        Threads_Delete,
        Threads_Lock,
        Threads_Unlock,
        Messages_Create,
        Messages_Edit,
        Messages_Delete,
        Messages_Update,
        Messages_PostImage,
        Messages_PostReply,
        Topics_Create,
        Topics_Edit,
        Topics_Delete
    }
}